version: '2'
services:
    web-core:
        build: web-client-core-asp.net
        ports:
        - "80:80"
        image: "esaipnet/web-client-core-asp:1.0"
    api-core:
        build: api-core.net
        ports:
        - "81:80"
        image: "esaipnet/api-core.net:1.0"
    api-node:
        build: api-node.js
        ports:
        - "82:80"
        image: "esaipnet/api-node.js:1.0"
    db-mongo:
        image: "mongo:3.0.3"